### ISSUE TITLE
[Bug] Retrieving denom price

### ISSUE THREAD

**Issue by yun-yeo** [stakewithus/oracle-voter#6]
https://github.com/stakewithus/oracle-voter/blob/f46d2db68c26393bfeeb9aa34efa889ebe21b6be/oracle-voter/oracle/machine2.py#L151

I think this part should be `median` or `mean` not just sum.

**Comment by olwee** [comment]
Yes, currently there is only 1 market, however it should be a mean nonetheless to future proof it
